#!/usr/bin/env python3
"""
gen_mp_node_layer.py
Generates MP_Node_Layer_BX_LY.v files with integrated layer norm.

Configure LAYERS list below, then run:
    python gen_mp_node_layer.py
"""

import os

# -----------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------
BLOCK_NO = 7
OUTPUT_DIR = "./"

LAYERS = [
    {
        "block"   : BLOCK_NO,
        "layer"   : 1,
        "neurons" : 32,
        "features": 32,
    }
]

DEFAULTS = {
    "prefix"           : "output",  # prefix for weight/bias MIF files
    "data_bits"        : 8,
    "weight_bits"      : 8,
    "bias_bits"        : 8,
    "done_delay"       : 1,        # cycles to wait after counter_done
    # Layer norm
    "ln_data_bits"     : 24,
    "ln_data_frac_bits": 10,
    "ln_scale_bits"    : 8,
    "ln_frac_bits"     : 6,
    "ln_inv_sqrt_bits" : 16,
    "ln_inv_sqrt_frac" : 11,
    "ln_var_bits"      : 45,
    "ln_lut_bits"      : 5,
    "ln_lut_size"      : 20,
    "ln_epsilon"       : 1,
    "ln_out_bits"      : 8,
    "ln_out_frac_bits" : 4,
}

# -----------------------------------------------------------------------
# Helper
# -----------------------------------------------------------------------
def cfg(layer_dict, key):
    return layer_dict.get(key, DEFAULTS[key])

# -----------------------------------------------------------------------
# Single neuron instance
# -----------------------------------------------------------------------
def gen_neuron_instance(n, cfg_d):
    prefix      = cfg(cfg_d, "prefix")
    block       = cfg_d["block"]
    layer       = cfg_d["layer"]
    num_features= cfg_d["features"]

    weight_file = f"{prefix}_w_{layer}_{n}.mif"
    bias_file   = f"{prefix}_b_{layer}_{n}.mif"

    return f"""
        if (NUM_NEURONS > {n}) begin : neuron_{n}
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("{weight_file}"),
                .BiasFile    ("{bias_file}")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[{n}])
            );
        end
"""

# -----------------------------------------------------------------------
# Full module
# -----------------------------------------------------------------------
def gen_module(cfg_d):
    block       = cfg_d["block"]
    layer       = cfg_d["layer"]
    num_neurons = cfg_d["neurons"]
    num_features= cfg_d["features"]
    prefix      = cfg(cfg_d, "prefix")
    done_delay  = cfg(cfg_d, "done_delay")

    data_bits        = cfg(cfg_d, "data_bits")
    weight_bits      = cfg(cfg_d, "weight_bits")
    bias_bits        = cfg(cfg_d, "bias_bits")
    ln_data_bits     = cfg(cfg_d, "ln_data_bits")
    ln_data_frac_bits= cfg(cfg_d, "ln_data_frac_bits")
    ln_scale_bits    = cfg(cfg_d, "ln_scale_bits")
    ln_frac_bits     = cfg(cfg_d, "ln_frac_bits")
    ln_inv_sqrt_bits = cfg(cfg_d, "ln_inv_sqrt_bits")
    ln_inv_sqrt_frac = cfg(cfg_d, "ln_inv_sqrt_frac")
    ln_var_bits      = cfg(cfg_d, "ln_var_bits")
    ln_lut_bits      = cfg(cfg_d, "ln_lut_bits")
    ln_lut_size      = cfg(cfg_d, "ln_lut_size")
    ln_epsilon       = cfg(cfg_d, "ln_epsilon")
    ln_out_bits      = cfg(cfg_d, "ln_out_bits")
    ln_out_frac_bits = cfg(cfg_d, "ln_out_frac_bits")

    module_name = f"Edge_Output_Layer"
    gamma_file  = f"ln_gamma_{layer}.mif"
    beta_file   = f"ln_beta_{layer}.mif"

    neuron_instances = "".join(
        gen_neuron_instance(n, cfg_d)
        for n in range(num_neurons)
    )

    # delay counter width: enough bits for done_delay value
    delay_bits = max(7, done_delay.bit_length() + 1) if isinstance(done_delay, int) else 7

    verilog = f"""`timescale 1ns / 1ps
//==============================================================================
// {module_name}.v  --  Auto-generated by gen_mp_edge_layer.py
//
// Block {block}, Layer {layer}
// {num_features} inputs -> {num_neurons} neurons -> layer norm -> {num_neurons} x {ln_out_bits}-bit Q4.4 outputs
//==============================================================================
module {module_name} #(
    parameter LAYER_NO        = {layer},
    parameter BLOCK_NO        = {block},
    parameter NUM_NEURONS     = {num_neurons},
    parameter NUM_FEATURES    = {num_features},
    parameter DATA_BITS       = {data_bits},
    parameter WEIGHT_BITS     = {weight_bits},
    parameter BIAS_BITS       = {bias_bits},
    // Layer norm
    parameter LN_DATA_BITS      = {ln_data_bits},
    parameter LN_DATA_FRAC_BITS = {ln_data_frac_bits},
    parameter LN_SCALE_BITS     = {ln_scale_bits},
    parameter LN_FRAC_BITS      = {ln_frac_bits},
    parameter LN_INV_SQRT_BITS  = {ln_inv_sqrt_bits},
    parameter LN_INV_SQRT_FRAC  = {ln_inv_sqrt_frac},
    parameter LN_VAR_BITS       = {ln_var_bits},
    parameter LN_LUT_BITS       = {ln_lut_bits},
    parameter LN_LUT_SIZE       = {ln_lut_size},
    parameter LN_EPSILON        = {ln_epsilon},
    parameter LN_OUT_BITS       = {ln_out_bits},
    parameter LN_OUT_FRAC_BITS  = {ln_out_frac_bits},
    parameter GammaFile         = "{gamma_file}",
    parameter BetaFile          = "{beta_file}"
)(
    input  clk,
    input  rstn,
    input  activation_function,
    input  start,
    input  signed [NUM_FEATURES*DATA_BITS-1:0]   data_in_flat,

    output signed [NUM_NEURONS*LN_OUT_BITS-1:0]  data_out_flat,  // Q4.4 per neuron
    output valid_out,                                          // layer norm done
    output done
);

    //--------------------------------------------------------------------------
    // Neuron output width
    //--------------------------------------------------------------------------
    localparam NEURON_OUT_BITS = DATA_BITS + WEIGHT_BITS + 8;

    //--------------------------------------------------------------------------
    // Counter -- uses start as rstn (matches original style)
    //--------------------------------------------------------------------------
    wire [31:0] counter;
    wire        counter_done;

    counter #(
        .END_COUNTER(NUM_FEATURES)
    ) layer_counter (
        .clk               (clk),
        .rstn              (start),
        .counter_out       (counter),
        .counter_donestatus(counter_done)
    );

    //--------------------------------------------------------------------------
    // Computation active + done state machine (matches original)
    //--------------------------------------------------------------------------
    reg computation_active;
    reg done_reg;
    reg [{delay_bits-1}:0] done_delay_counter;

    always @(posedge clk or negedge rstn) begin
        if (!rstn) begin
            computation_active <= 0;
            done_reg           <= 0;
            done_delay_counter <= 0;
        end else begin
            if (start && !computation_active && !done_reg) begin
                computation_active <= 1;
                done_reg           <= 0;
                done_delay_counter <= 0;
            end else if (counter_done && computation_active && !done_reg) begin
                if (done_delay_counter < {done_delay}) begin
                    done_delay_counter <= done_delay_counter + 1;
                    done_reg           <= 0;
                end else begin
                    done_reg           <= 1;
                    done_delay_counter <= 0;
                end
            end else if (done_reg && start) begin
                computation_active <= 1;
                done_reg           <= 0;
                done_delay_counter <= 0;
            end
        end
    end

    assign done = done_reg;

    //--------------------------------------------------------------------------
    // Raw neuron outputs
    //--------------------------------------------------------------------------
    wire signed [NEURON_OUT_BITS-1:0] neuron_outputs [0:NUM_NEURONS-1];

    //--------------------------------------------------------------------------
    // Layer norm input bus
    //--------------------------------------------------------------------------
    reg signed [NUM_NEURONS*LN_DATA_BITS-1:0] ln_data_in;

    //--------------------------------------------------------------------------
    // Gamma / Beta -- load from MIF into array, pack into flat bus
    //--------------------------------------------------------------------------
    reg signed [LN_SCALE_BITS-1:0] gamma_arr [0:NUM_NEURONS-1];
    reg signed [LN_SCALE_BITS-1:0] beta_arr  [0:NUM_NEURONS-1];

    reg signed [NUM_NEURONS*LN_SCALE_BITS-1:0] ln_gamma;
    reg signed [NUM_NEURONS*LN_SCALE_BITS-1:0] ln_beta;

    integer g;
    initial begin
        $readmemb(GammaFile, gamma_arr);
        $readmemb(BetaFile,  beta_arr);
        for (g = 0; g < NUM_NEURONS; g = g + 1) begin
            ln_gamma[g*LN_SCALE_BITS +: LN_SCALE_BITS] = gamma_arr[g];
            ln_beta [g*LN_SCALE_BITS +: LN_SCALE_BITS] = beta_arr [g];
        end
    end

    //--------------------------------------------------------------------------
    // Edge detect done_reg rising edge -> 1-cycle pulse to layer norm
    // done_reg goes high after the neuron delay, so neurons are stable
    //--------------------------------------------------------------------------
    reg  done_reg_r;
    reg  ln_start;

    always @(posedge clk or negedge rstn) begin
        if (!rstn) begin
            done_reg_r <= 1'b0;
            ln_start   <= 1'b0;
        end else begin
            done_reg_r <= done_reg;
            // Rising edge of done_reg = neurons settled, safe to start LN
            ln_start   <= done_reg & ~done_reg_r;
        end
    end

    //--------------------------------------------------------------------------
    // Latch + sign-extend neuron outputs into ln_data_in on ln_start pulse
    //--------------------------------------------------------------------------
    integer n;
    always @(posedge clk or negedge rstn) begin
        if (!rstn) begin
            ln_data_in <= {{(NUM_NEURONS*LN_DATA_BITS){{1'b0}}}};
        end else if (ln_start) begin
            for (n = 0; n < NUM_NEURONS; n = n + 1) begin
                ln_data_in[n*LN_DATA_BITS +: LN_DATA_BITS] <=
                    {{{{(LN_DATA_BITS-NEURON_OUT_BITS){{neuron_outputs[n][NEURON_OUT_BITS-1]}}}},
                      neuron_outputs[n]}};
            end
        end
    end

    //--------------------------------------------------------------------------
    // Layer norm instance
    //--------------------------------------------------------------------------
    layer_norm #(
        .NUM_FEATURES      (NUM_NEURONS),
        .DATA_BITS         (LN_DATA_BITS),
        .DATA_FRAC_BITS    (LN_DATA_FRAC_BITS),
        .SCALE_BITS        (LN_SCALE_BITS),
        .FRAC_BITS         (LN_FRAC_BITS),
        .INV_SQRT_BITS     (LN_INV_SQRT_BITS),
        .INV_SQRT_FRAC_BITS(LN_INV_SQRT_FRAC),
        .VAR_BITS          (LN_VAR_BITS),
        .LUT_BITS          (LN_LUT_BITS),
        .LUT_SIZE          (LN_LUT_SIZE),
        .EPSILON           (LN_EPSILON),
        .OUT_BITS          (LN_OUT_BITS),
        .OUT_FRAC_BITS     (LN_OUT_FRAC_BITS)
    ) u_layer_norm (
        .clk      (clk),
        .rstn     (rstn),
        .valid_in (ln_start),
        .act_en   (activation_function),
        .data_in  (ln_data_in),
        .gamma    (ln_gamma),
        .beta     (ln_beta),
        .valid_out(valid_out),
        .busy     (),
        .data_out (data_out_flat)
    );

    //--------------------------------------------------------------------------
    // Neuron instances
    //--------------------------------------------------------------------------
    generate
{neuron_instances}
    endgenerate

endmodule
"""
    return verilog


# -----------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------
def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    for layer_cfg in LAYERS:
        block       = layer_cfg["block"]
        layer       = layer_cfg["layer"]
        module_name = f"Edge_Output_Layer"
        filename    = os.path.join(OUTPUT_DIR, f"{module_name}.v")

        print(f"Generating {module_name}: "
              f"{layer_cfg['features']} features -> "
              f"{layer_cfg['neurons']} neurons -> "
              f"{cfg(layer_cfg, 'ln_out_bits')}-bit Q4.4 output")

        verilog = gen_module(layer_cfg)

        with open(filename, "w", encoding="utf-8") as f:
            f.write(verilog)

        print(f"  Written: {filename}")

    print(f"\nDone. {len(LAYERS)} file(s) written to '{OUTPUT_DIR}/'")


if __name__ == "__main__":
    main()