`timescale 1ns / 1ps
//==============================================================================
// MP_Node_Layer_B1_L3.v  --  Auto-generated by gen_mp_node_layer.py
//
// Block 1, Layer 3
// 64 inputs -> 64 neurons -> layer norm -> 64 x 8-bit Q4.4 outputs
//==============================================================================
module MP_Node_Layer_B1_L3 #(
    parameter LAYER_NO        = 3,
    parameter BLOCK_NO        = 1,
    parameter NUM_NEURONS     = 64,
    parameter NUM_FEATURES    = 64,
    parameter DATA_BITS       = 8,
    parameter WEIGHT_BITS     = 8,
    parameter BIAS_BITS       = 8,
    // Layer norm
    parameter LN_DATA_BITS      = 24,
    parameter LN_DATA_FRAC_BITS = 10,
    parameter LN_SCALE_BITS     = 8,
    parameter LN_FRAC_BITS      = 6,
    parameter LN_INV_SQRT_BITS  = 16,
    parameter LN_INV_SQRT_FRAC  = 11,
    parameter LN_VAR_BITS       = 45,
    parameter LN_LUT_BITS       = 5,
    parameter LN_LUT_SIZE       = 20,
    parameter LN_EPSILON        = 1,
    parameter LN_OUT_BITS       = 8,
    parameter LN_OUT_FRAC_BITS  = 4,
    parameter GammaFile         = "ln_gamma_3.mif",
    parameter BetaFile          = "ln_beta_3.mif"
)(
    input  clk,
    input  rstn,
    input  activation_function,
    input  start,
    input  signed [NUM_FEATURES*DATA_BITS-1:0]   data_in_flat,

    output signed [NUM_NEURONS*LN_OUT_BITS-1:0]  data_out_flat,  // Q4.4 per neuron
    output valid_out,                                          // layer norm done
    output done
);

    //--------------------------------------------------------------------------
    // Neuron output width
    //--------------------------------------------------------------------------
    localparam NEURON_OUT_BITS = DATA_BITS + WEIGHT_BITS + 8;

    //--------------------------------------------------------------------------
    // Counter -- uses start as rstn (matches original style)
    //--------------------------------------------------------------------------
    wire [31:0] counter;
    wire        counter_done;

    counter #(
        .END_COUNTER(NUM_FEATURES)
    ) layer_counter (
        .clk               (clk),
        .rstn              (start),
        .counter_out       (counter),
        .counter_donestatus(counter_done)
    );

    //--------------------------------------------------------------------------
    // Computation active + done state machine (matches original)
    //--------------------------------------------------------------------------
    reg computation_active;
    reg done_reg;
    reg [6:0] done_delay_counter;

    always @(posedge clk or negedge rstn) begin
        if (!rstn) begin
            computation_active <= 0;
            done_reg           <= 0;
            done_delay_counter <= 0;
        end else begin
            if (start && !computation_active && !done_reg) begin
                computation_active <= 1;
                done_reg           <= 0;
                done_delay_counter <= 0;
            end else if (counter_done && computation_active && !done_reg) begin
                if (done_delay_counter < 1) begin
                    done_delay_counter <= done_delay_counter + 1;
                    done_reg           <= 0;
                end else begin
                    done_reg           <= 1;
                    done_delay_counter <= 0;
                end
            end else if (done_reg && start) begin
                computation_active <= 1;
                done_reg           <= 0;
                done_delay_counter <= 0;
            end
        end
    end

    assign done = done_reg;

    //--------------------------------------------------------------------------
    // Raw neuron outputs
    //--------------------------------------------------------------------------
    wire signed [NEURON_OUT_BITS-1:0] neuron_outputs [0:NUM_NEURONS-1];

    //--------------------------------------------------------------------------
    // Layer norm input bus
    //--------------------------------------------------------------------------
    reg signed [NUM_NEURONS*LN_DATA_BITS-1:0] ln_data_in;

    //--------------------------------------------------------------------------
    // Gamma / Beta -- load from MIF into array, pack into flat bus
    //--------------------------------------------------------------------------
    reg signed [LN_SCALE_BITS-1:0] gamma_arr [0:NUM_NEURONS-1];
    reg signed [LN_SCALE_BITS-1:0] beta_arr  [0:NUM_NEURONS-1];

    reg signed [NUM_NEURONS*LN_SCALE_BITS-1:0] ln_gamma;
    reg signed [NUM_NEURONS*LN_SCALE_BITS-1:0] ln_beta;

    integer g;
    initial begin
        $readmemb(GammaFile, gamma_arr);
        $readmemb(BetaFile,  beta_arr);
        for (g = 0; g < NUM_NEURONS; g = g + 1) begin
            ln_gamma[g*LN_SCALE_BITS +: LN_SCALE_BITS] = gamma_arr[g];
            ln_beta [g*LN_SCALE_BITS +: LN_SCALE_BITS] = beta_arr [g];
        end
    end

    //--------------------------------------------------------------------------
    // Edge detect done_reg rising edge -> 1-cycle pulse to layer norm
    // done_reg goes high after the neuron delay, so neurons are stable
    //--------------------------------------------------------------------------
    reg  done_reg_r;
    reg  ln_start;

    always @(posedge clk or negedge rstn) begin
        if (!rstn) begin
            done_reg_r <= 1'b0;
            ln_start   <= 1'b0;
        end else begin
            done_reg_r <= done_reg;
            // Rising edge of done_reg = neurons settled, safe to start LN
            ln_start   <= done_reg & ~done_reg_r;
        end
    end

    //--------------------------------------------------------------------------
    // Latch + sign-extend neuron outputs into ln_data_in on ln_start pulse
    //--------------------------------------------------------------------------
    integer n;
    always @(posedge clk or negedge rstn) begin
        if (!rstn) begin
            ln_data_in <= {(NUM_NEURONS*LN_DATA_BITS){1'b0}};
        end else if (ln_start) begin
            for (n = 0; n < NUM_NEURONS; n = n + 1) begin
                ln_data_in[n*LN_DATA_BITS +: LN_DATA_BITS] <=
                    {{(LN_DATA_BITS-NEURON_OUT_BITS){neuron_outputs[n][NEURON_OUT_BITS-1]}},
                      neuron_outputs[n]};
            end
        end
    end

    //--------------------------------------------------------------------------
    // Layer norm instance
    //--------------------------------------------------------------------------
    layer_norm #(
        .NUM_FEATURES      (NUM_NEURONS),
        .DATA_BITS         (LN_DATA_BITS),
        .DATA_FRAC_BITS    (LN_DATA_FRAC_BITS),
        .SCALE_BITS        (LN_SCALE_BITS),
        .FRAC_BITS         (LN_FRAC_BITS),
        .INV_SQRT_BITS     (LN_INV_SQRT_BITS),
        .INV_SQRT_FRAC_BITS(LN_INV_SQRT_FRAC),
        .VAR_BITS          (LN_VAR_BITS),
        .LUT_BITS          (LN_LUT_BITS),
        .LUT_SIZE          (LN_LUT_SIZE),
        .EPSILON           (LN_EPSILON),
        .OUT_BITS          (LN_OUT_BITS),
        .OUT_FRAC_BITS     (LN_OUT_FRAC_BITS)
    ) u_layer_norm (
        .clk      (clk),
        .rstn     (rstn),
        .valid_in (ln_start),
        .act_en   (activation_function),
        .data_in  (ln_data_in),
        .gamma    (ln_gamma),
        .beta     (ln_beta),
        .valid_out(valid_out),
        .busy     (),
        .data_out (data_out_flat)
    );

    //--------------------------------------------------------------------------
    // Neuron instances
    //--------------------------------------------------------------------------
    generate

        if (NUM_NEURONS > 0) begin : neuron_0
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_0.mif"),
                .BiasFile    ("mp_node_b_1_3_0.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[0])
            );
        end

        if (NUM_NEURONS > 1) begin : neuron_1
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_1.mif"),
                .BiasFile    ("mp_node_b_1_3_1.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[1])
            );
        end

        if (NUM_NEURONS > 2) begin : neuron_2
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_2.mif"),
                .BiasFile    ("mp_node_b_1_3_2.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[2])
            );
        end

        if (NUM_NEURONS > 3) begin : neuron_3
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_3.mif"),
                .BiasFile    ("mp_node_b_1_3_3.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[3])
            );
        end

        if (NUM_NEURONS > 4) begin : neuron_4
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_4.mif"),
                .BiasFile    ("mp_node_b_1_3_4.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[4])
            );
        end

        if (NUM_NEURONS > 5) begin : neuron_5
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_5.mif"),
                .BiasFile    ("mp_node_b_1_3_5.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[5])
            );
        end

        if (NUM_NEURONS > 6) begin : neuron_6
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_6.mif"),
                .BiasFile    ("mp_node_b_1_3_6.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[6])
            );
        end

        if (NUM_NEURONS > 7) begin : neuron_7
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_7.mif"),
                .BiasFile    ("mp_node_b_1_3_7.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[7])
            );
        end

        if (NUM_NEURONS > 8) begin : neuron_8
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_8.mif"),
                .BiasFile    ("mp_node_b_1_3_8.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[8])
            );
        end

        if (NUM_NEURONS > 9) begin : neuron_9
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_9.mif"),
                .BiasFile    ("mp_node_b_1_3_9.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[9])
            );
        end

        if (NUM_NEURONS > 10) begin : neuron_10
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_10.mif"),
                .BiasFile    ("mp_node_b_1_3_10.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[10])
            );
        end

        if (NUM_NEURONS > 11) begin : neuron_11
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_11.mif"),
                .BiasFile    ("mp_node_b_1_3_11.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[11])
            );
        end

        if (NUM_NEURONS > 12) begin : neuron_12
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_12.mif"),
                .BiasFile    ("mp_node_b_1_3_12.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[12])
            );
        end

        if (NUM_NEURONS > 13) begin : neuron_13
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_13.mif"),
                .BiasFile    ("mp_node_b_1_3_13.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[13])
            );
        end

        if (NUM_NEURONS > 14) begin : neuron_14
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_14.mif"),
                .BiasFile    ("mp_node_b_1_3_14.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[14])
            );
        end

        if (NUM_NEURONS > 15) begin : neuron_15
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_15.mif"),
                .BiasFile    ("mp_node_b_1_3_15.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[15])
            );
        end

        if (NUM_NEURONS > 16) begin : neuron_16
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_16.mif"),
                .BiasFile    ("mp_node_b_1_3_16.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[16])
            );
        end

        if (NUM_NEURONS > 17) begin : neuron_17
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_17.mif"),
                .BiasFile    ("mp_node_b_1_3_17.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[17])
            );
        end

        if (NUM_NEURONS > 18) begin : neuron_18
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_18.mif"),
                .BiasFile    ("mp_node_b_1_3_18.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[18])
            );
        end

        if (NUM_NEURONS > 19) begin : neuron_19
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_19.mif"),
                .BiasFile    ("mp_node_b_1_3_19.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[19])
            );
        end

        if (NUM_NEURONS > 20) begin : neuron_20
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_20.mif"),
                .BiasFile    ("mp_node_b_1_3_20.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[20])
            );
        end

        if (NUM_NEURONS > 21) begin : neuron_21
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_21.mif"),
                .BiasFile    ("mp_node_b_1_3_21.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[21])
            );
        end

        if (NUM_NEURONS > 22) begin : neuron_22
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_22.mif"),
                .BiasFile    ("mp_node_b_1_3_22.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[22])
            );
        end

        if (NUM_NEURONS > 23) begin : neuron_23
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_23.mif"),
                .BiasFile    ("mp_node_b_1_3_23.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[23])
            );
        end

        if (NUM_NEURONS > 24) begin : neuron_24
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_24.mif"),
                .BiasFile    ("mp_node_b_1_3_24.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[24])
            );
        end

        if (NUM_NEURONS > 25) begin : neuron_25
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_25.mif"),
                .BiasFile    ("mp_node_b_1_3_25.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[25])
            );
        end

        if (NUM_NEURONS > 26) begin : neuron_26
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_26.mif"),
                .BiasFile    ("mp_node_b_1_3_26.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[26])
            );
        end

        if (NUM_NEURONS > 27) begin : neuron_27
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_27.mif"),
                .BiasFile    ("mp_node_b_1_3_27.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[27])
            );
        end

        if (NUM_NEURONS > 28) begin : neuron_28
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_28.mif"),
                .BiasFile    ("mp_node_b_1_3_28.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[28])
            );
        end

        if (NUM_NEURONS > 29) begin : neuron_29
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_29.mif"),
                .BiasFile    ("mp_node_b_1_3_29.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[29])
            );
        end

        if (NUM_NEURONS > 30) begin : neuron_30
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_30.mif"),
                .BiasFile    ("mp_node_b_1_3_30.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[30])
            );
        end

        if (NUM_NEURONS > 31) begin : neuron_31
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_31.mif"),
                .BiasFile    ("mp_node_b_1_3_31.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[31])
            );
        end

        if (NUM_NEURONS > 32) begin : neuron_32
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_32.mif"),
                .BiasFile    ("mp_node_b_1_3_32.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[32])
            );
        end

        if (NUM_NEURONS > 33) begin : neuron_33
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_33.mif"),
                .BiasFile    ("mp_node_b_1_3_33.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[33])
            );
        end

        if (NUM_NEURONS > 34) begin : neuron_34
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_34.mif"),
                .BiasFile    ("mp_node_b_1_3_34.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[34])
            );
        end

        if (NUM_NEURONS > 35) begin : neuron_35
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_35.mif"),
                .BiasFile    ("mp_node_b_1_3_35.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[35])
            );
        end

        if (NUM_NEURONS > 36) begin : neuron_36
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_36.mif"),
                .BiasFile    ("mp_node_b_1_3_36.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[36])
            );
        end

        if (NUM_NEURONS > 37) begin : neuron_37
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_37.mif"),
                .BiasFile    ("mp_node_b_1_3_37.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[37])
            );
        end

        if (NUM_NEURONS > 38) begin : neuron_38
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_38.mif"),
                .BiasFile    ("mp_node_b_1_3_38.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[38])
            );
        end

        if (NUM_NEURONS > 39) begin : neuron_39
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_39.mif"),
                .BiasFile    ("mp_node_b_1_3_39.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[39])
            );
        end

        if (NUM_NEURONS > 40) begin : neuron_40
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_40.mif"),
                .BiasFile    ("mp_node_b_1_3_40.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[40])
            );
        end

        if (NUM_NEURONS > 41) begin : neuron_41
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_41.mif"),
                .BiasFile    ("mp_node_b_1_3_41.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[41])
            );
        end

        if (NUM_NEURONS > 42) begin : neuron_42
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_42.mif"),
                .BiasFile    ("mp_node_b_1_3_42.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[42])
            );
        end

        if (NUM_NEURONS > 43) begin : neuron_43
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_43.mif"),
                .BiasFile    ("mp_node_b_1_3_43.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[43])
            );
        end

        if (NUM_NEURONS > 44) begin : neuron_44
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_44.mif"),
                .BiasFile    ("mp_node_b_1_3_44.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[44])
            );
        end

        if (NUM_NEURONS > 45) begin : neuron_45
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_45.mif"),
                .BiasFile    ("mp_node_b_1_3_45.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[45])
            );
        end

        if (NUM_NEURONS > 46) begin : neuron_46
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_46.mif"),
                .BiasFile    ("mp_node_b_1_3_46.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[46])
            );
        end

        if (NUM_NEURONS > 47) begin : neuron_47
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_47.mif"),
                .BiasFile    ("mp_node_b_1_3_47.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[47])
            );
        end

        if (NUM_NEURONS > 48) begin : neuron_48
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_48.mif"),
                .BiasFile    ("mp_node_b_1_3_48.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[48])
            );
        end

        if (NUM_NEURONS > 49) begin : neuron_49
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_49.mif"),
                .BiasFile    ("mp_node_b_1_3_49.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[49])
            );
        end

        if (NUM_NEURONS > 50) begin : neuron_50
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_50.mif"),
                .BiasFile    ("mp_node_b_1_3_50.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[50])
            );
        end

        if (NUM_NEURONS > 51) begin : neuron_51
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_51.mif"),
                .BiasFile    ("mp_node_b_1_3_51.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[51])
            );
        end

        if (NUM_NEURONS > 52) begin : neuron_52
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_52.mif"),
                .BiasFile    ("mp_node_b_1_3_52.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[52])
            );
        end

        if (NUM_NEURONS > 53) begin : neuron_53
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_53.mif"),
                .BiasFile    ("mp_node_b_1_3_53.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[53])
            );
        end

        if (NUM_NEURONS > 54) begin : neuron_54
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_54.mif"),
                .BiasFile    ("mp_node_b_1_3_54.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[54])
            );
        end

        if (NUM_NEURONS > 55) begin : neuron_55
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_55.mif"),
                .BiasFile    ("mp_node_b_1_3_55.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[55])
            );
        end

        if (NUM_NEURONS > 56) begin : neuron_56
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_56.mif"),
                .BiasFile    ("mp_node_b_1_3_56.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[56])
            );
        end

        if (NUM_NEURONS > 57) begin : neuron_57
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_57.mif"),
                .BiasFile    ("mp_node_b_1_3_57.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[57])
            );
        end

        if (NUM_NEURONS > 58) begin : neuron_58
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_58.mif"),
                .BiasFile    ("mp_node_b_1_3_58.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[58])
            );
        end

        if (NUM_NEURONS > 59) begin : neuron_59
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_59.mif"),
                .BiasFile    ("mp_node_b_1_3_59.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[59])
            );
        end

        if (NUM_NEURONS > 60) begin : neuron_60
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_60.mif"),
                .BiasFile    ("mp_node_b_1_3_60.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[60])
            );
        end

        if (NUM_NEURONS > 61) begin : neuron_61
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_61.mif"),
                .BiasFile    ("mp_node_b_1_3_61.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[61])
            );
        end

        if (NUM_NEURONS > 62) begin : neuron_62
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_62.mif"),
                .BiasFile    ("mp_node_b_1_3_62.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[62])
            );
        end

        if (NUM_NEURONS > 63) begin : neuron_63
            neuron #(
                .NEURON_WIDTH(NUM_FEATURES),
                .DATA_BITS   (DATA_BITS),
                .WEIGHT_BITS (WEIGHT_BITS),
                .BIAS_BITS   (BIAS_BITS),
                .WeightFile  ("mp_node_w_1_3_63.mif"),
                .BiasFile    ("mp_node_b_1_3_63.mif")
            ) inst (
                .clk                (clk),
                .rstn               (rstn),
                .activation_function(activation_function),
                .data_in_flat       (data_in_flat),
                .counter            (counter),
                .data_out           (neuron_outputs[63])
            );
        end

    endgenerate

endmodule
